# Generated by Django 2.1.3 on 2018-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0003_auto_20181211_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('meio_pagamento', models.CharField(max_length=255, verbose_name='Pagamento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Dinheiro ')),
                ('valor_taxa_entrega', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Taxa Entrega')),
                ('acrescimos', models.ManyToManyField(to='produto.Item')),
                ('produtos', models.ManyToManyField(to='produto.Produto')),
            ],
        ),
    ]
