# Generated by Django 2.1.3 on 2018-12-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20181211_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='acrescimos',
            field=models.ManyToManyField(to='item.Item'),
        ),
    ]
