# Generated by Django 2.1.3 on 2018-12-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_auto_20181211_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='acrescimos',
            field=models.ManyToManyField(blank=True, to='item.Item'),
        ),
    ]
