# Generated by Django 2.1.3 on 2018-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('itens', models.ManyToManyField(to='produto.Item')),
            ],
        ),
    ]
